server {
    # Nginx container internal port 80 par listen karega
    listen 80;
    
    # Catch-all server name. Actual domain resolution K8s Ingress handle karega.
    server_name _;

    # Yeh wahi exact destination path hai jahan Dockerfile ki COPY command files paste karegi
    root /usr/share/nginx/html;
    
    # Entry point
    index index.html;

    # Single Page Application (SPA) Routing Logic
    location / {
        # 1. $uri: Pehle exact physical file dhoondhega (jaise .js, .css, images)
        # 2. $uri/: Agar file nahi mili, toh exact directory dhoondhega
        # 3. /index.html: Agar kuch nahi mila, toh 404 error dene ki jagah index.html return karega
        try_files $uri $uri/ /index.html;
    }

    # Optimization: Static files caching (Recommended for Production)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}